%% Autonomous RVD and docking in the CR3BP %% 
% Sergio Cuevas del Valle % 
% 01/04/21 % 

%% Vector field protrait %% 
% This script provides an interface to plot the vector field generated by several dynamical models. 

% The relative motion of two spacecraft in two halo orbits around L1 in the
% Earth-Moon system is analyzed both from the direct integration of the
% equations of motion and the full motion relative motion 

% Units are non-dimensional and solutions are expressed in the Lagrange
% points reference frame as defined by Howell, 1984.

%% Set up %%
%Set up graphics 
set_graphics();

%% Contants and initial data %% 
%CR3BP constants 
mu = 0.0121505;                        %Earth-Moon reduced gravitational parameter
L = libration_points(mu);              %System libration points
Lem = 384400e3;                        %Mean distance from the Earth to the Moon

%Differential corrector set up
nodes = 10;                            %Number of nodes for the multiple shooting corrector
maxIter = 20;                          %Maximum number of iterations
tol = 1e-10;                           %Differential corrector tolerance

%Halo characteristics 
Az = 200e6;                                                 %Orbit amplitude out of the synodic plane. 
Az = dimensionalizer(Lem, 1, 1, Az, 'Position', 0);         %Normalize distances for the E-M system
Ln = 1;                                                     %Orbits around L1
gamma = L(end,Ln);                                          %Li distance to the second primary
m = 1;                                                      %Number of periods to compute

%Compute a halo seed 
halo_param = [1 Az Ln gamma m];                             %Northern halo parameters
[halo_seed, period] = object_seed(mu, halo_param, 'Halo');  %Generate a halo orbit seed

%Correct the seed and obtain initial conditions for a halo orbit
[target_orbit, ~] = differential_correction('Plane Symmetric', mu, halo_seed, maxIter, tol);

%% Initial conditions %%
ds = 0.1;                              %Spatial step
hmax = 1.1;                            %Maximum distance from the synodic origin
hmin = 0;                              %Minimum distance from the synodic origin
x = linspace(0.7, 1, 10);              %Synodic x coordinate
y = linspace(hmin, hmax, 10);          %Synodic y coordinate
z = linspace(hmin, hmax, 10);          %Synodic z coordinate

%% Modelling in the synodic frame %% 
%Preallocation 
S = zeros(length(x), length(y), length(z), 12);     

%Compute the vector field
for i = 1:length(x)
    for j = 1:length(y)
        for k = 1:length(z)
            s = [target_orbit.Trajectory(1,1:6).'; x(i); y(j); z(k); target_orbit.Trajectory(1,4:6).'];
            S(i,j,k,1:12) = nlr_model(mu, true, false, 'Encke', 0, s);
        end
    end
end

%% Results %% 
%Plot results 
K = 1;
figure(1) 
view(3) 
hold on
for i = 1:length(x) 
    for j = 1:length(y)
        for k = 1:length(z)
            quiver3(x(i), y(j), z(k), K*S(i,j,k,7), K*S(i,j,k,8), K*S(i,j,k,9), 'r');
        end
    end
end
hold off
grid on;
xlabel('Synodic x coordinate');
ylabel('Synodic y coordinate');
zlabel('Synodic z coordinate');
title('Vector field portrait');